//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mostafa_Mahmod_W4
{
    using System;
    using System.Collections.Generic;
    
    public partial class userr
    {
        public int user_idd { get; set; }
        public string Username { get; set; }
        public string pasword { get; set; }
        public Nullable<int> age { get; set; }
        public string Gender { get; set; }
        public string phone_number { get; set; }
        public string city { get; set; }
    }
}
